version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/project/
      - ./:/docker/
    volumes_from:
      - storage
  storage:
    build:
      context: docker/storage/
    volumes:
      - /storage